// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mt4-term-api-demo-account.proto

package mt4_term_api;

public final class Mt4TermApiDemoAccount {
  private Mt4TermApiDemoAccount() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DemoAccountStreamEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mt4_term_api.DemoAccountStreamEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string step = 1;</code>
     * @return The step.
     */
    java.lang.String getStep();
    /**
     * <code>string step = 1;</code>
     * @return The bytes for step.
     */
    com.google.protobuf.ByteString
        getStepBytes();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>string level = 3;</code>
     * @return The level.
     */
    java.lang.String getLevel();
    /**
     * <code>string level = 3;</code>
     * @return The bytes for level.
     */
    com.google.protobuf.ByteString
        getLevelBytes();

    /**
     * <code>int64 elapsed_ms = 4;</code>
     * @return The elapsedMs.
     */
    long getElapsedMs();

    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     * @return The timestamp.
     */
    com.google.protobuf.Timestamp getTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

    /**
     * <code>bool is_final = 6;</code>
     * @return The isFinal.
     */
    boolean getIsFinal();

    /**
     * <code>.mt4_term_api.GuiDemoOpenAccountReply account_data = 7;</code>
     * @return Whether the accountData field is set.
     */
    boolean hasAccountData();
    /**
     * <code>.mt4_term_api.GuiDemoOpenAccountReply account_data = 7;</code>
     * @return The accountData.
     */
    mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply getAccountData();
    /**
     * <code>.mt4_term_api.GuiDemoOpenAccountReply account_data = 7;</code>
     */
    mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReplyOrBuilder getAccountDataOrBuilder();
  }
  /**
   * <pre>
   * Event message streamed during OpenDemoAccountStream.
   * </pre>
   *
   * Protobuf type {@code mt4_term_api.DemoAccountStreamEvent}
   */
  public static final class DemoAccountStreamEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mt4_term_api.DemoAccountStreamEvent)
      DemoAccountStreamEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DemoAccountStreamEvent.newBuilder() to construct.
    private DemoAccountStreamEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DemoAccountStreamEvent() {
      step_ = "";
      message_ = "";
      level_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DemoAccountStreamEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DemoAccountStreamEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              step_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              level_ = s;
              break;
            }
            case 32: {

              elapsedMs_ = input.readInt64();
              break;
            }
            case 42: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (timestamp_ != null) {
                subBuilder = timestamp_.toBuilder();
              }
              timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timestamp_);
                timestamp_ = subBuilder.buildPartial();
              }

              break;
            }
            case 48: {

              isFinal_ = input.readBool();
              break;
            }
            case 58: {
              mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply.Builder subBuilder = null;
              if (accountData_ != null) {
                subBuilder = accountData_.toBuilder();
              }
              accountData_ = input.readMessage(mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(accountData_);
                accountData_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mt4_term_api.Mt4TermApiDemoAccount.internal_static_mt4_term_api_DemoAccountStreamEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mt4_term_api.Mt4TermApiDemoAccount.internal_static_mt4_term_api_DemoAccountStreamEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent.class, mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent.Builder.class);
    }

    public static final int STEP_FIELD_NUMBER = 1;
    private volatile java.lang.Object step_;
    /**
     * <code>string step = 1;</code>
     * @return The step.
     */
    @java.lang.Override
    public java.lang.String getStep() {
      java.lang.Object ref = step_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        step_ = s;
        return s;
      }
    }
    /**
     * <code>string step = 1;</code>
     * @return The bytes for step.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStepBytes() {
      java.lang.Object ref = step_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        step_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVEL_FIELD_NUMBER = 3;
    private volatile java.lang.Object level_;
    /**
     * <code>string level = 3;</code>
     * @return The level.
     */
    @java.lang.Override
    public java.lang.String getLevel() {
      java.lang.Object ref = level_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        level_ = s;
        return s;
      }
    }
    /**
     * <code>string level = 3;</code>
     * @return The bytes for level.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLevelBytes() {
      java.lang.Object ref = level_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        level_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ELAPSED_MS_FIELD_NUMBER = 4;
    private long elapsedMs_;
    /**
     * <code>int64 elapsed_ms = 4;</code>
     * @return The elapsedMs.
     */
    @java.lang.Override
    public long getElapsedMs() {
      return elapsedMs_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp timestamp_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return timestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTimestamp() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      return getTimestamp();
    }

    public static final int IS_FINAL_FIELD_NUMBER = 6;
    private boolean isFinal_;
    /**
     * <code>bool is_final = 6;</code>
     * @return The isFinal.
     */
    @java.lang.Override
    public boolean getIsFinal() {
      return isFinal_;
    }

    public static final int ACCOUNT_DATA_FIELD_NUMBER = 7;
    private mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply accountData_;
    /**
     * <code>.mt4_term_api.GuiDemoOpenAccountReply account_data = 7;</code>
     * @return Whether the accountData field is set.
     */
    @java.lang.Override
    public boolean hasAccountData() {
      return accountData_ != null;
    }
    /**
     * <code>.mt4_term_api.GuiDemoOpenAccountReply account_data = 7;</code>
     * @return The accountData.
     */
    @java.lang.Override
    public mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply getAccountData() {
      return accountData_ == null ? mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply.getDefaultInstance() : accountData_;
    }
    /**
     * <code>.mt4_term_api.GuiDemoOpenAccountReply account_data = 7;</code>
     */
    @java.lang.Override
    public mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReplyOrBuilder getAccountDataOrBuilder() {
      return getAccountData();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(step_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, step_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(level_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, level_);
      }
      if (elapsedMs_ != 0L) {
        output.writeInt64(4, elapsedMs_);
      }
      if (timestamp_ != null) {
        output.writeMessage(5, getTimestamp());
      }
      if (isFinal_ != false) {
        output.writeBool(6, isFinal_);
      }
      if (accountData_ != null) {
        output.writeMessage(7, getAccountData());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(step_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, step_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(level_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, level_);
      }
      if (elapsedMs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, elapsedMs_);
      }
      if (timestamp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getTimestamp());
      }
      if (isFinal_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isFinal_);
      }
      if (accountData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getAccountData());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent)) {
        return super.equals(obj);
      }
      mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent other = (mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent) obj;

      if (!getStep()
          .equals(other.getStep())) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getLevel()
          .equals(other.getLevel())) return false;
      if (getElapsedMs()
          != other.getElapsedMs()) return false;
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (!getTimestamp()
            .equals(other.getTimestamp())) return false;
      }
      if (getIsFinal()
          != other.getIsFinal()) return false;
      if (hasAccountData() != other.hasAccountData()) return false;
      if (hasAccountData()) {
        if (!getAccountData()
            .equals(other.getAccountData())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STEP_FIELD_NUMBER;
      hash = (53 * hash) + getStep().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel().hashCode();
      hash = (37 * hash) + ELAPSED_MS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getElapsedMs());
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      hash = (37 * hash) + IS_FINAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsFinal());
      if (hasAccountData()) {
        hash = (37 * hash) + ACCOUNT_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getAccountData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Event message streamed during OpenDemoAccountStream.
     * </pre>
     *
     * Protobuf type {@code mt4_term_api.DemoAccountStreamEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mt4_term_api.DemoAccountStreamEvent)
        mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mt4_term_api.Mt4TermApiDemoAccount.internal_static_mt4_term_api_DemoAccountStreamEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mt4_term_api.Mt4TermApiDemoAccount.internal_static_mt4_term_api_DemoAccountStreamEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent.class, mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent.Builder.class);
      }

      // Construct using mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        step_ = "";

        message_ = "";

        level_ = "";

        elapsedMs_ = 0L;

        if (timestampBuilder_ == null) {
          timestamp_ = null;
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }
        isFinal_ = false;

        if (accountDataBuilder_ == null) {
          accountData_ = null;
        } else {
          accountData_ = null;
          accountDataBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mt4_term_api.Mt4TermApiDemoAccount.internal_static_mt4_term_api_DemoAccountStreamEvent_descriptor;
      }

      @java.lang.Override
      public mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent getDefaultInstanceForType() {
        return mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent.getDefaultInstance();
      }

      @java.lang.Override
      public mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent build() {
        mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent buildPartial() {
        mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent result = new mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent(this);
        result.step_ = step_;
        result.message_ = message_;
        result.level_ = level_;
        result.elapsedMs_ = elapsedMs_;
        if (timestampBuilder_ == null) {
          result.timestamp_ = timestamp_;
        } else {
          result.timestamp_ = timestampBuilder_.build();
        }
        result.isFinal_ = isFinal_;
        if (accountDataBuilder_ == null) {
          result.accountData_ = accountData_;
        } else {
          result.accountData_ = accountDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent) {
          return mergeFrom((mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent other) {
        if (other == mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent.getDefaultInstance()) return this;
        if (!other.getStep().isEmpty()) {
          step_ = other.step_;
          onChanged();
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (!other.getLevel().isEmpty()) {
          level_ = other.level_;
          onChanged();
        }
        if (other.getElapsedMs() != 0L) {
          setElapsedMs(other.getElapsedMs());
        }
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        if (other.getIsFinal() != false) {
          setIsFinal(other.getIsFinal());
        }
        if (other.hasAccountData()) {
          mergeAccountData(other.getAccountData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object step_ = "";
      /**
       * <code>string step = 1;</code>
       * @return The step.
       */
      public java.lang.String getStep() {
        java.lang.Object ref = step_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          step_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string step = 1;</code>
       * @return The bytes for step.
       */
      public com.google.protobuf.ByteString
          getStepBytes() {
        java.lang.Object ref = step_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          step_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string step = 1;</code>
       * @param value The step to set.
       * @return This builder for chaining.
       */
      public Builder setStep(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        step_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string step = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStep() {
        
        step_ = getDefaultInstance().getStep();
        onChanged();
        return this;
      }
      /**
       * <code>string step = 1;</code>
       * @param value The bytes for step to set.
       * @return This builder for chaining.
       */
      public Builder setStepBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        step_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object level_ = "";
      /**
       * <code>string level = 3;</code>
       * @return The level.
       */
      public java.lang.String getLevel() {
        java.lang.Object ref = level_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          level_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string level = 3;</code>
       * @return The bytes for level.
       */
      public com.google.protobuf.ByteString
          getLevelBytes() {
        java.lang.Object ref = level_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          level_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string level = 3;</code>
       * @param value The level to set.
       * @return This builder for chaining.
       */
      public Builder setLevel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string level = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLevel() {
        
        level_ = getDefaultInstance().getLevel();
        onChanged();
        return this;
      }
      /**
       * <code>string level = 3;</code>
       * @param value The bytes for level to set.
       * @return This builder for chaining.
       */
      public Builder setLevelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        level_ = value;
        onChanged();
        return this;
      }

      private long elapsedMs_ ;
      /**
       * <code>int64 elapsed_ms = 4;</code>
       * @return The elapsedMs.
       */
      @java.lang.Override
      public long getElapsedMs() {
        return elapsedMs_;
      }
      /**
       * <code>int64 elapsed_ms = 4;</code>
       * @param value The elapsedMs to set.
       * @return This builder for chaining.
       */
      public Builder setElapsedMs(long value) {
        
        elapsedMs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 elapsed_ms = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearElapsedMs() {
        
        elapsedMs_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp timestamp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       * @return Whether the timestamp field is set.
       */
      public boolean hasTimestamp() {
        return timestampBuilder_ != null || timestamp_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       * @return The timestamp.
       */
      public com.google.protobuf.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
          onChanged();
        } else {
          timestampBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public Builder setTimestamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
          onChanged();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (timestamp_ != null) {
            timestamp_ =
              com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
          } else {
            timestamp_ = value;
          }
          onChanged();
        } else {
          timestampBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public Builder clearTimestamp() {
        if (timestampBuilder_ == null) {
          timestamp_ = null;
          onChanged();
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
        
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTimestamp(),
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }

      private boolean isFinal_ ;
      /**
       * <code>bool is_final = 6;</code>
       * @return The isFinal.
       */
      @java.lang.Override
      public boolean getIsFinal() {
        return isFinal_;
      }
      /**
       * <code>bool is_final = 6;</code>
       * @param value The isFinal to set.
       * @return This builder for chaining.
       */
      public Builder setIsFinal(boolean value) {
        
        isFinal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_final = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsFinal() {
        
        isFinal_ = false;
        onChanged();
        return this;
      }

      private mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply accountData_;
      private com.google.protobuf.SingleFieldBuilderV3<
          mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply, mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply.Builder, mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReplyOrBuilder> accountDataBuilder_;
      /**
       * <code>.mt4_term_api.GuiDemoOpenAccountReply account_data = 7;</code>
       * @return Whether the accountData field is set.
       */
      public boolean hasAccountData() {
        return accountDataBuilder_ != null || accountData_ != null;
      }
      /**
       * <code>.mt4_term_api.GuiDemoOpenAccountReply account_data = 7;</code>
       * @return The accountData.
       */
      public mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply getAccountData() {
        if (accountDataBuilder_ == null) {
          return accountData_ == null ? mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply.getDefaultInstance() : accountData_;
        } else {
          return accountDataBuilder_.getMessage();
        }
      }
      /**
       * <code>.mt4_term_api.GuiDemoOpenAccountReply account_data = 7;</code>
       */
      public Builder setAccountData(mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply value) {
        if (accountDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          accountData_ = value;
          onChanged();
        } else {
          accountDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.mt4_term_api.GuiDemoOpenAccountReply account_data = 7;</code>
       */
      public Builder setAccountData(
          mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply.Builder builderForValue) {
        if (accountDataBuilder_ == null) {
          accountData_ = builderForValue.build();
          onChanged();
        } else {
          accountDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.mt4_term_api.GuiDemoOpenAccountReply account_data = 7;</code>
       */
      public Builder mergeAccountData(mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply value) {
        if (accountDataBuilder_ == null) {
          if (accountData_ != null) {
            accountData_ =
              mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply.newBuilder(accountData_).mergeFrom(value).buildPartial();
          } else {
            accountData_ = value;
          }
          onChanged();
        } else {
          accountDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.mt4_term_api.GuiDemoOpenAccountReply account_data = 7;</code>
       */
      public Builder clearAccountData() {
        if (accountDataBuilder_ == null) {
          accountData_ = null;
          onChanged();
        } else {
          accountData_ = null;
          accountDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.mt4_term_api.GuiDemoOpenAccountReply account_data = 7;</code>
       */
      public mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply.Builder getAccountDataBuilder() {
        
        onChanged();
        return getAccountDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.mt4_term_api.GuiDemoOpenAccountReply account_data = 7;</code>
       */
      public mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReplyOrBuilder getAccountDataOrBuilder() {
        if (accountDataBuilder_ != null) {
          return accountDataBuilder_.getMessageOrBuilder();
        } else {
          return accountData_ == null ?
              mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply.getDefaultInstance() : accountData_;
        }
      }
      /**
       * <code>.mt4_term_api.GuiDemoOpenAccountReply account_data = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply, mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply.Builder, mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReplyOrBuilder> 
          getAccountDataFieldBuilder() {
        if (accountDataBuilder_ == null) {
          accountDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply, mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReply.Builder, mt4_term_api.Mt4TermApiGui.GuiDemoOpenAccountReplyOrBuilder>(
                  getAccountData(),
                  getParentForChildren(),
                  isClean());
          accountData_ = null;
        }
        return accountDataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mt4_term_api.DemoAccountStreamEvent)
    }

    // @@protoc_insertion_point(class_scope:mt4_term_api.DemoAccountStreamEvent)
    private static final mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent();
    }

    public static mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DemoAccountStreamEvent>
        PARSER = new com.google.protobuf.AbstractParser<DemoAccountStreamEvent>() {
      @java.lang.Override
      public DemoAccountStreamEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DemoAccountStreamEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DemoAccountStreamEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DemoAccountStreamEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mt4_term_api.Mt4TermApiDemoAccount.DemoAccountStreamEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mt4_term_api_DemoAccountStreamEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mt4_term_api_DemoAccountStreamEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037mt4-term-api-demo-account.proto\022\014mt4_t" +
      "erm_api\032\034google/api/annotations.proto\032\026m" +
      "t4-term-api-gui.proto\032\037google/protobuf/t" +
      "imestamp.proto\"\330\001\n\026DemoAccountStreamEven" +
      "t\022\014\n\004step\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\r\n\005leve" +
      "l\030\003 \001(\t\022\022\n\nelapsed_ms\030\004 \001(\003\022-\n\ttimestamp" +
      "\030\005 \001(\0132\032.google.protobuf.Timestamp\022\020\n\010is" +
      "_final\030\006 \001(\010\022;\n\014account_data\030\007 \001(\0132%.mt4" +
      "_term_api.GuiDemoOpenAccountReply2\301\004\n\013De" +
      "moAccount\022\207\001\n\rFindCompanies\022).mt4_term_a" +
      "pi.GuiDemoFindCompaniesRequest\032\'.mt4_ter" +
      "m_api.GuiDemoFindCompaniesReply\"\"\202\323\344\223\002\034\022" +
      "\032/DemoAccount/FindCompanies\022\235\001\n\026ServersA" +
      "ndAccountTypes\022+.mt4_term_api.GuiDemoSer" +
      "versAndTypesRequest\032).mt4_term_api.GuiDe" +
      "moServersAndTypesReply\"+\202\323\344\223\002%\022#/DemoAcc" +
      "ount/ServersAndAccountTypes\022|\n\017OpenDemoA" +
      "ccount\022\'.mt4_term_api.GuiDemoOpenAccount" +
      "Request\032%.mt4_term_api.GuiDemoOpenAccoun" +
      "tReply\"\031\202\323\344\223\002\023\022\021/DemoAccount/Open\022\211\001\n\025Op" +
      "enDemoAccountStream\022\'.mt4_term_api.GuiDe" +
      "moOpenAccountRequest\032$.mt4_term_api.Demo" +
      "AccountStreamEvent\"\037\202\323\344\223\002\031\022\027/DemoAccount" +
      "/OpenStream0\001BBZ1git.mtapi.io/root/mrpc-" +
      "proto.git/mt4/libraries/go\252\002\014mt4_term_ap" +
      "ib\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          mt4_term_api.Mt4TermApiGui.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_mt4_term_api_DemoAccountStreamEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mt4_term_api_DemoAccountStreamEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mt4_term_api_DemoAccountStreamEvent_descriptor,
        new java.lang.String[] { "Step", "Message", "Level", "ElapsedMs", "Timestamp", "IsFinal", "AccountData", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    mt4_term_api.Mt4TermApiGui.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
