// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mt4-term-api-health-check.proto

package mt4_term_api;

public final class Mt4TermApiHealthCheck {
  private Mt4TermApiHealthCheck() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HealthCheckRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mt4_term_api.HealthCheckRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code mt4_term_api.HealthCheckRequest}
   */
  public static final class HealthCheckRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mt4_term_api.HealthCheckRequest)
      HealthCheckRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HealthCheckRequest.newBuilder() to construct.
    private HealthCheckRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HealthCheckRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HealthCheckRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HealthCheckRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mt4_term_api.Mt4TermApiHealthCheck.internal_static_mt4_term_api_HealthCheckRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mt4_term_api.Mt4TermApiHealthCheck.internal_static_mt4_term_api_HealthCheckRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest.class, mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest)) {
        return super.equals(obj);
      }
      mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest other = (mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mt4_term_api.HealthCheckRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mt4_term_api.HealthCheckRequest)
        mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mt4_term_api.Mt4TermApiHealthCheck.internal_static_mt4_term_api_HealthCheckRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mt4_term_api.Mt4TermApiHealthCheck.internal_static_mt4_term_api_HealthCheckRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest.class, mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest.Builder.class);
      }

      // Construct using mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mt4_term_api.Mt4TermApiHealthCheck.internal_static_mt4_term_api_HealthCheckRequest_descriptor;
      }

      @java.lang.Override
      public mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest getDefaultInstanceForType() {
        return mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest.getDefaultInstance();
      }

      @java.lang.Override
      public mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest build() {
        mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest buildPartial() {
        mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest result = new mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest) {
          return mergeFrom((mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest other) {
        if (other == mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mt4_term_api.HealthCheckRequest)
    }

    // @@protoc_insertion_point(class_scope:mt4_term_api.HealthCheckRequest)
    private static final mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest();
    }

    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HealthCheckRequest>
        PARSER = new com.google.protobuf.AbstractParser<HealthCheckRequest>() {
      @java.lang.Override
      public HealthCheckRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HealthCheckRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HealthCheckRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HealthCheckRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mt4_term_api.Mt4TermApiHealthCheck.HealthCheckRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HealthCheckReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mt4_term_api.HealthCheckReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool connected = 1;</code>
     * @return The connected.
     */
    boolean getConnected();

    /**
     * <code>int64 serverTimeMsc = 2;</code>
     * @return The serverTimeMsc.
     */
    long getServerTimeMsc();
  }
  /**
   * Protobuf type {@code mt4_term_api.HealthCheckReply}
   */
  public static final class HealthCheckReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mt4_term_api.HealthCheckReply)
      HealthCheckReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HealthCheckReply.newBuilder() to construct.
    private HealthCheckReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HealthCheckReply() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HealthCheckReply();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HealthCheckReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              connected_ = input.readBool();
              break;
            }
            case 16: {

              serverTimeMsc_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mt4_term_api.Mt4TermApiHealthCheck.internal_static_mt4_term_api_HealthCheckReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mt4_term_api.Mt4TermApiHealthCheck.internal_static_mt4_term_api_HealthCheckReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply.class, mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply.Builder.class);
    }

    public static final int CONNECTED_FIELD_NUMBER = 1;
    private boolean connected_;
    /**
     * <code>bool connected = 1;</code>
     * @return The connected.
     */
    @java.lang.Override
    public boolean getConnected() {
      return connected_;
    }

    public static final int SERVERTIMEMSC_FIELD_NUMBER = 2;
    private long serverTimeMsc_;
    /**
     * <code>int64 serverTimeMsc = 2;</code>
     * @return The serverTimeMsc.
     */
    @java.lang.Override
    public long getServerTimeMsc() {
      return serverTimeMsc_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (connected_ != false) {
        output.writeBool(1, connected_);
      }
      if (serverTimeMsc_ != 0L) {
        output.writeInt64(2, serverTimeMsc_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (connected_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, connected_);
      }
      if (serverTimeMsc_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, serverTimeMsc_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply)) {
        return super.equals(obj);
      }
      mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply other = (mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply) obj;

      if (getConnected()
          != other.getConnected()) return false;
      if (getServerTimeMsc()
          != other.getServerTimeMsc()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONNECTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getConnected());
      hash = (37 * hash) + SERVERTIMEMSC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getServerTimeMsc());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mt4_term_api.HealthCheckReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mt4_term_api.HealthCheckReply)
        mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mt4_term_api.Mt4TermApiHealthCheck.internal_static_mt4_term_api_HealthCheckReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mt4_term_api.Mt4TermApiHealthCheck.internal_static_mt4_term_api_HealthCheckReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply.class, mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply.Builder.class);
      }

      // Construct using mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        connected_ = false;

        serverTimeMsc_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mt4_term_api.Mt4TermApiHealthCheck.internal_static_mt4_term_api_HealthCheckReply_descriptor;
      }

      @java.lang.Override
      public mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply getDefaultInstanceForType() {
        return mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply.getDefaultInstance();
      }

      @java.lang.Override
      public mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply build() {
        mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply buildPartial() {
        mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply result = new mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply(this);
        result.connected_ = connected_;
        result.serverTimeMsc_ = serverTimeMsc_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply) {
          return mergeFrom((mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply other) {
        if (other == mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply.getDefaultInstance()) return this;
        if (other.getConnected() != false) {
          setConnected(other.getConnected());
        }
        if (other.getServerTimeMsc() != 0L) {
          setServerTimeMsc(other.getServerTimeMsc());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean connected_ ;
      /**
       * <code>bool connected = 1;</code>
       * @return The connected.
       */
      @java.lang.Override
      public boolean getConnected() {
        return connected_;
      }
      /**
       * <code>bool connected = 1;</code>
       * @param value The connected to set.
       * @return This builder for chaining.
       */
      public Builder setConnected(boolean value) {
        
        connected_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool connected = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearConnected() {
        
        connected_ = false;
        onChanged();
        return this;
      }

      private long serverTimeMsc_ ;
      /**
       * <code>int64 serverTimeMsc = 2;</code>
       * @return The serverTimeMsc.
       */
      @java.lang.Override
      public long getServerTimeMsc() {
        return serverTimeMsc_;
      }
      /**
       * <code>int64 serverTimeMsc = 2;</code>
       * @param value The serverTimeMsc to set.
       * @return This builder for chaining.
       */
      public Builder setServerTimeMsc(long value) {
        
        serverTimeMsc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 serverTimeMsc = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerTimeMsc() {
        
        serverTimeMsc_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mt4_term_api.HealthCheckReply)
    }

    // @@protoc_insertion_point(class_scope:mt4_term_api.HealthCheckReply)
    private static final mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply();
    }

    public static mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HealthCheckReply>
        PARSER = new com.google.protobuf.AbstractParser<HealthCheckReply>() {
      @java.lang.Override
      public HealthCheckReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HealthCheckReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HealthCheckReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HealthCheckReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mt4_term_api.Mt4TermApiHealthCheck.HealthCheckReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CloseTerminalRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mt4_term_api.CloseTerminalRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code mt4_term_api.CloseTerminalRequest}
   */
  public static final class CloseTerminalRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mt4_term_api.CloseTerminalRequest)
      CloseTerminalRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CloseTerminalRequest.newBuilder() to construct.
    private CloseTerminalRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CloseTerminalRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CloseTerminalRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CloseTerminalRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mt4_term_api.Mt4TermApiHealthCheck.internal_static_mt4_term_api_CloseTerminalRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mt4_term_api.Mt4TermApiHealthCheck.internal_static_mt4_term_api_CloseTerminalRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest.class, mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest)) {
        return super.equals(obj);
      }
      mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest other = (mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mt4_term_api.CloseTerminalRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mt4_term_api.CloseTerminalRequest)
        mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mt4_term_api.Mt4TermApiHealthCheck.internal_static_mt4_term_api_CloseTerminalRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mt4_term_api.Mt4TermApiHealthCheck.internal_static_mt4_term_api_CloseTerminalRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest.class, mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest.Builder.class);
      }

      // Construct using mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mt4_term_api.Mt4TermApiHealthCheck.internal_static_mt4_term_api_CloseTerminalRequest_descriptor;
      }

      @java.lang.Override
      public mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest getDefaultInstanceForType() {
        return mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest.getDefaultInstance();
      }

      @java.lang.Override
      public mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest build() {
        mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest buildPartial() {
        mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest result = new mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest) {
          return mergeFrom((mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest other) {
        if (other == mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mt4_term_api.CloseTerminalRequest)
    }

    // @@protoc_insertion_point(class_scope:mt4_term_api.CloseTerminalRequest)
    private static final mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest();
    }

    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CloseTerminalRequest>
        PARSER = new com.google.protobuf.AbstractParser<CloseTerminalRequest>() {
      @java.lang.Override
      public CloseTerminalRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CloseTerminalRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CloseTerminalRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CloseTerminalRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CloseTerminalReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mt4_term_api.CloseTerminalReply)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code mt4_term_api.CloseTerminalReply}
   */
  public static final class CloseTerminalReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mt4_term_api.CloseTerminalReply)
      CloseTerminalReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CloseTerminalReply.newBuilder() to construct.
    private CloseTerminalReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CloseTerminalReply() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CloseTerminalReply();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CloseTerminalReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mt4_term_api.Mt4TermApiHealthCheck.internal_static_mt4_term_api_CloseTerminalReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mt4_term_api.Mt4TermApiHealthCheck.internal_static_mt4_term_api_CloseTerminalReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply.class, mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply)) {
        return super.equals(obj);
      }
      mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply other = (mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mt4_term_api.CloseTerminalReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mt4_term_api.CloseTerminalReply)
        mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mt4_term_api.Mt4TermApiHealthCheck.internal_static_mt4_term_api_CloseTerminalReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mt4_term_api.Mt4TermApiHealthCheck.internal_static_mt4_term_api_CloseTerminalReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply.class, mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply.Builder.class);
      }

      // Construct using mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mt4_term_api.Mt4TermApiHealthCheck.internal_static_mt4_term_api_CloseTerminalReply_descriptor;
      }

      @java.lang.Override
      public mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply getDefaultInstanceForType() {
        return mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply.getDefaultInstance();
      }

      @java.lang.Override
      public mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply build() {
        mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply buildPartial() {
        mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply result = new mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply) {
          return mergeFrom((mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply other) {
        if (other == mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mt4_term_api.CloseTerminalReply)
    }

    // @@protoc_insertion_point(class_scope:mt4_term_api.CloseTerminalReply)
    private static final mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply();
    }

    public static mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CloseTerminalReply>
        PARSER = new com.google.protobuf.AbstractParser<CloseTerminalReply>() {
      @java.lang.Override
      public CloseTerminalReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CloseTerminalReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CloseTerminalReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CloseTerminalReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mt4_term_api.Mt4TermApiHealthCheck.CloseTerminalReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mt4_term_api_HealthCheckRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mt4_term_api_HealthCheckRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mt4_term_api_HealthCheckReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mt4_term_api_HealthCheckReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mt4_term_api_CloseTerminalRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mt4_term_api_CloseTerminalRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mt4_term_api_CloseTerminalReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mt4_term_api_CloseTerminalReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037mt4-term-api-health-check.proto\022\014mt4_t" +
      "erm_api\"\024\n\022HealthCheckRequest\"<\n\020HealthC" +
      "heckReply\022\021\n\tconnected\030\001 \001(\010\022\025\n\rserverTi" +
      "meMsc\030\002 \001(\003\"\026\n\024CloseTerminalRequest\"\024\n\022C" +
      "loseTerminalReply2\267\001\n\rHealthService\022O\n\013H" +
      "ealthCheck\022 .mt4_term_api.HealthCheckReq" +
      "uest\032\036.mt4_term_api.HealthCheckReply\022U\n\r" +
      "CloseTerminal\022\".mt4_term_api.CloseTermin" +
      "alRequest\032 .mt4_term_api.CloseTerminalRe" +
      "plyBBZ1git.mtapi.io/root/mrpc-proto.git/" +
      "mt4/libraries/go\252\002\014mt4_term_apib\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mt4_term_api_HealthCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mt4_term_api_HealthCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mt4_term_api_HealthCheckRequest_descriptor,
        new java.lang.String[] { });
    internal_static_mt4_term_api_HealthCheckReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mt4_term_api_HealthCheckReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mt4_term_api_HealthCheckReply_descriptor,
        new java.lang.String[] { "Connected", "ServerTimeMsc", });
    internal_static_mt4_term_api_CloseTerminalRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mt4_term_api_CloseTerminalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mt4_term_api_CloseTerminalRequest_descriptor,
        new java.lang.String[] { });
    internal_static_mt4_term_api_CloseTerminalReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_mt4_term_api_CloseTerminalReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mt4_term_api_CloseTerminalReply_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
